#name: Dynamic Database Update from Changed Folders
name: Geoserver updates

on: push

jobs:
  update-database:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Setting up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.AWS_KEY }}" > ~/.ssh/id_aws.pem
        chmod 600 ~/.ssh/id_aws.pem
        ssh-keyscan -H ec2-34-224-89-239.compute-1.amazonaws.com >> ~/.ssh/known_hosts

    - name: Identify changed directories and files
      id: dir_changes
      run: |
        ssh -i "~/.ssh/id_aws.pem" ubuntu@ec2-34-224-89-239.compute-1.amazonaws.com '/home/ubuntu/run_commands.sh'

